disabled_rules:
  - empty_enum_arguments

identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - app
    - acc
    - id
    - URL
    - url
    - GlobalAPIKey
reporter: "xcode"
